# Generated by Django 5.2.1 on 2025-09-10 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=2025)),
                ('daily_price', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('capacity', models.IntegerField()),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('tiptronic', 'Tiptronic')], default='automatic', max_length=20)),
                ('city', models.CharField(default='kutaisi', max_length=50)),
                ('fuel_tank', models.IntegerField(default=1)),
                ('photo1', models.ImageField(default='cars/default1.jpg', upload_to='cars/')),
                ('photo2', models.ImageField(default='cars/default2.jpg', upload_to='cars/')),
                ('photo3', models.ImageField(default='cars/default3.jpg', upload_to='cars/')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
