# Generated by Django 5.2.1 on 2025-09-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_daily_price_alter_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rent_count',
            field=models.IntegerField(default=0),
        ),
    ]
