# Generated by Django 5.2.1 on 2025-09-14 09:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_rent_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_cars', to=settings.AUTH_USER_MODEL),
        ),
    ]
