# Generated by Django 5.2.1 on 2025-09-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo1',
            field=models.ImageField(default='default_car/default1.jpg', upload_to='cars/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo2',
            field=models.ImageField(default='default_car/default1.jpg', upload_to='cars/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo3',
            field=models.ImageField(default='default_car/default1.jpg', upload_to='cars/'),
        ),
    ]
